### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/block-on-spring#16]
This repo does not have a readme!

**Comment by jeffugo** [comment]
I'd love to work on this one.

**Comment by arichar6** [comment]
> I'd love to work on this one.

Awesome! Let me know if you have any questions about this.

**Comment by jeffugo** [comment]
@arichar6 thanks you! I understand that a readme introduces and explains a project. How do I get myself acquainted with this project?

**Comment by arichar6** [comment]
The best way to get started with this project is to clone and run it. 
1) Clone this repo
2) Create a new conda environment using the `environment.yml` file
3) Run the code using `python run.py`

**Comment by arichar6** [comment]
@jeffugo How's the readme file going? I'm thinking about adding a minimal readme file, which could then be expanded. Would that help?

**Comment by arichar6** [comment]
The readme was created in commit a9938f9435cc48e99d0eee7534db4ad66aa584dd
