### ISSUE TITLE
Generate tutorial based on this example?

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/block-on-spring#5]
What do you think about creating a "turboPy app tutorial" based on this simple app? It could be a fairly straightforward project, which I think could be completed in a reasonable amount of time. As our PM and intern-admin, I'd like to get your thoughts on this.

@GarethTMorgan @carolinegsun

**Comment by arichar6** [comment]
Since `pip install turbopy` now works, this repo can now connect to mybinder. Try this out, then enter `import turbopy` in the notebook that opens up:

https://mybinder.org/v2/gh/NRL-Plasma-Physics-Division/block-on-spring/main?filepath=docs%2Fnotebooks%2Ftest.ipynb

@padamson you might get a kick out of this

**Comment by padamson** [comment]
Very cool and good to know. Thanks!

**Comment by AOstenfeld** [comment]
I've spent some time learning the basics of the Jupyter notebook and I'd be interested in working on this, but I'm not really sure where to start. Should the "tutorial" more or less be an explaination of how to set up and run the block on spring app?

**Comment by padamson** [comment]
I would look at the [PlasmaPy examples](https://docs.plasmapy.org/en/latest/examples.html) for inspiration on what makes a good example notebook for this type of repo.

**Comment by AOstenfeld** [comment]
How do you add a Jupyter notebook to github? If I try to add a file with the ipynb extension nothing appears.

**Comment by arichar6** [comment]
Check that your .gitignore isn't preventing you from adding files with extension `.ipynb`.

**Comment by AOstenfeld** [comment]
The block_on_spring .gitignore doesn't seem to ignore .ipynb files, and there's already a test.ipynb file on the repo. However, if I try to create a new file with the .ipynb extension, a notebook doesn't appear. it loads for a few seconds and then says that something went wrong.

**Comment by arichar6** [comment]
What "loads for a few seconds"? And what is the error message? Can you describe the steps you tried?

**Comment by AOstenfeld** [comment]
Sorry i've been so vague. I clicked add file in github and named the file tutorial.ipynb. When I click on the file to edit it, it just says "something went wrong"

**Comment by arichar6** [comment]
That's probably because a jupyter notebook has a specific format that it uses (structured plain text). It was probably trying to parse the notebook format, but couldn't because it was just a blank file.

You should create the notebook on your local machine first. That way you can also get it tested and working before creating a PR to add it to the repo.

**Comment by arichar6** [comment]
Thanks @AOstenfeld for your work on this notebook!
